module.exports = {
	NUM_RESOURCES: 3,
	NUM_NEIGHBORS: 6,
	CONNECTOR_WEIGHT: 0.33,
	MAX_HEIGHT: 16,
	DECIMALS: 18,
	PRECISION: 1e6,
	PURCHASE_MARKUP: 1/3,
	TAX_RATE: 1/6,
	MINIMUM_TILE_PRICE: 0.025,
	ONITE_BLOCK: 0,
	TOPITE_BLOCK: 1,
	RUBITE_BLOCK: 2,
	ERRORS: [
		'MAX_HEIGHT',
		'NOT_ALLOWED',
		'ALREADY',
		'INSUFFICIENT',
		'RESTRICTED',
		'UNINITIALIZED',
		'TIME_TRAVEL',
		'INVALID',
		'NOT_FOUND'
	]
};
